name: ci

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MacOS 12 x86_64
            os: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: ./unwind
